//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Monolito_4Am.Dashboard {
    public partial class Admin {
        protected global::System.Web.UI.WebControls.LinkButton btnCerrarSesion;
        protected global::System.Web.UI.WebControls.Label lblTotalUsers;
        protected global::System.Web.UI.WebControls.Label lblLockedUsers;
        protected global::System.Web.UI.WebControls.Label lblTodayActions;
        protected global::System.Web.UI.WebControls.TextBox txtAdminCedula;
        protected global::System.Web.UI.WebControls.TextBox txtAdminNombres;
        protected global::System.Web.UI.WebControls.TextBox txtAdminApellidos;
        protected global::System.Web.UI.WebControls.TextBox txtAdminCorreo;
        protected global::System.Web.UI.WebControls.TextBox txtAdminNick;
        protected global::System.Web.UI.WebControls.TextBox txtAdminPass;
        protected global::System.Web.UI.WebControls.Button btnCrearAdmin;
        protected global::System.Web.UI.WebControls.Label lblMsgAdmin;
        protected global::System.Web.UI.WebControls.Panel pnlEditor;
        protected global::System.Web.UI.WebControls.Label lblEditNick;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseEditor;
        protected global::System.Web.UI.WebControls.HiddenField hfEditId;
        protected global::System.Web.UI.WebControls.TextBox txtEditCedula;
        protected global::System.Web.UI.WebControls.TextBox txtEditCorreo;
        protected global::System.Web.UI.WebControls.TextBox txtEditNombres;
        protected global::System.Web.UI.WebControls.TextBox txtEditApellidos;
        protected global::System.Web.UI.WebControls.Button btnGuardarCambios;
        protected global::System.Web.UI.WebControls.GridView gvBloqueados;
        protected global::System.Web.UI.WebControls.Image imgFoto;
        protected global::System.Web.UI.WebControls.Button btnDesbloquear;
        protected global::System.Web.UI.WebControls.LinkButton btnRefreshUsers;
        protected global::System.Web.UI.WebControls.GridView gvTodos;
        protected global::System.Web.UI.WebControls.Image imgFotoAll;
        protected global::System.Web.UI.WebControls.LinkButton btnEditar;
        protected global::System.Web.UI.WebControls.LinkButton btnToggle;
        protected global::System.Web.UI.WebControls.LinkButton btnRefreshLogs;
        protected global::System.Web.UI.WebControls.GridView gvLogs;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}

