//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Monolito_4Am.Dashboard {
    public partial class Usuario {
        protected global::System.Web.UI.WebControls.Label lblUserNick;
        protected global::System.Web.UI.WebControls.Image imgAvatar;
        protected global::System.Web.UI.WebControls.LinkButton btnCerrarSesion;
        protected global::System.Web.UI.WebControls.Label lblNombres;
        protected global::System.Web.UI.WebControls.HyperLink lnkJuego;
        protected global::System.Web.UI.WebControls.Repeater rptLeaderboard;
        protected global::System.Web.UI.WebControls.Repeater rptMisPuntajes;
        protected global::System.Web.UI.UpdatePanel upPerfil;
        protected global::System.Web.UI.WebControls.Image imgFotoPerfil;
        protected global::System.Web.UI.WebControls.FileUpload fupNuevoFoto;
        protected global::System.Web.UI.WebControls.Button btnPrevNuevoFoto;
        protected global::System.Web.UI.WebControls.Button btnSubirFoto;
        protected global::System.Web.UI.WebControls.Image imgNuevoFotoPreview;
        protected global::System.Web.UI.WebControls.Repeater rptGaleria;
        protected global::System.Web.UI.WebControls.FileUpload fupGaleria;
        protected global::System.Web.UI.WebControls.Button btnSubirGaleria;
        protected global::System.Web.UI.WebControls.Panel pnlMsgPerfil;
        protected global::System.Web.UI.WebControls.Label lblMsgPerfil;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl secPerfil;
    }
}

