//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolito_4Am.Mantenimineto {
    
    
    public partial class estadisticas_producto {
        
        /// <summary>
        /// Control form1.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// Control btnVolver.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnVolver;
        
        /// <summary>
        /// Control carouselInner.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl carouselInner;
    }
}
