//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Monolito_4Am.Mantenimineto {
    public partial class listar_tbl_proveedor {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.LinkButton btnNuevo;
        protected global::System.Web.UI.WebControls.GridView gvProveedores;
    }
}
