//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Monolito_4Am.Mantenimineto {
    public partial class listar_tbl_producto {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.LinkButton btnNuevo;
        protected global::System.Web.UI.WebControls.LinkButton btnExportarExcel;
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltro;
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;
        protected global::System.Web.UI.WebControls.LinkButton btnBuscar;
        protected global::System.Web.UI.WebControls.LinkButton btnLimpiar;
        protected global::System.Web.UI.WebControls.Label lblInfo;
        protected global::System.Web.UI.WebControls.GridView gvProductos;
        protected global::System.Web.UI.WebControls.LinkButton btnEditar;
        protected global::System.Web.UI.WebControls.LinkButton btnEliminar;
    }
}
