//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolito_4Am.Mantenimineto {

    public partial class nuevo_tbl_producto {

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.LinkButton btnBack;

        protected global::System.Web.UI.WebControls.Panel pnlForm;

        protected global::System.Web.UI.WebControls.TextBox txtCodigo;

        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;

        protected global::System.Web.UI.WebControls.TextBox txtPrecio;

        protected global::System.Web.UI.WebControls.TextBox txtCantidad;

        protected global::System.Web.UI.WebControls.DropDownList ddlProveedor;

        protected global::System.Web.UI.WebControls.PlaceHolder phCarruselActual;

        protected global::System.Web.UI.WebControls.HiddenField hfFotosEliminar;

        protected global::System.Web.UI.WebControls.Repeater rptCurrentImages;

        protected global::System.Web.UI.WebControls.FileUpload fuImagen;

        protected global::System.Web.UI.WebControls.LinkButton btnGuardar;

        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTitle;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblMensaje;
    }
}
