//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Monolito_4Am.Mantenimineto {
    public partial class subida_excel {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.FileUpload fuArchivo;
        protected global::System.Web.UI.WebControls.LinkButton btnPrevisualizar;
        protected global::System.Web.UI.WebControls.LinkButton btnProcesar;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl msgDiv;
        protected global::System.Web.UI.WebControls.Panel pnlStats;
        protected global::System.Web.UI.WebControls.Label lblNuevos;
        protected global::System.Web.UI.WebControls.Label lblActualizar;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Panel pnlPreview;
        protected global::System.Web.UI.WebControls.GridView gvPreview;
    }
}
