$files = Get-ChildItem -Path . -Recurse -Filter "*.aspx"
foreach ($f in $files) {
    $content = Get-Content $f.FullName -Raw
    $className = [regex]::Match($content, 'Inherits="([^"]+)"').Groups[1].Value
    if (-not $className) { continue }
    $namespace = ""
    $classOnly = $className
    if ($className.Contains(".")) {
        $idx = $className.LastIndexOf(".")
        $namespace = $className.Substring(0, $idx)
        $classOnly = $className.Substring($idx + 1)
    }

    $controls = [regex]::Matches($content, '<asp:(\w+)[^>]*\sID="([^"]+)"', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    # Solo buscamos tags que NO sean asp:
    $htmlControls = [regex]::Matches($content, '<(?!asp:)(\w+)[^>]*\s(?:ID|id)="([^"]+)"[^>]*runat="server"|<(?!asp:)(\w+)[^>]*runat="server"[^>]*\s(?:ID|id)="([^"]+)"', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)

    $sb = New-Object System.Text.StringBuilder
    $sb.AppendLine("//------------------------------------------------------------------------------") | Out-Null
    $sb.AppendLine("// <auto-generated>") | Out-Null
    $sb.AppendLine("//     This code was generated by a tool.") | Out-Null
    $sb.AppendLine("// </auto-generated>") | Out-Null
    $sb.AppendLine("//------------------------------------------------------------------------------") | Out-Null
    if ($namespace) { $sb.AppendLine("namespace $namespace {") | Out-Null }
    $sb.AppendLine("    public partial class $classOnly {") | Out-Null

    foreach ($m in $controls) {
        $typeName = $m.Groups[1].Value
        $type = "System.Web.UI.WebControls." + $typeName
        if ($typeName -eq "ScriptManager" -or $typeName -eq "UpdatePanel" -or $typeName -eq "Timer") {
            $type = "System.Web.UI." + $typeName
        }
        $id = $m.Groups[2].Value
        $sb.AppendLine("        protected global::$type $id;") | Out-Null
    }
    foreach ($m in $htmlControls) {
        $typeName = if ($m.Groups[1].Value) { $m.Groups[1].Value } else { $m.Groups[3].Value }
        $id = if ($m.Groups[2].Value) { $m.Groups[2].Value } else { $m.Groups[4].Value }
        
        $type = "System.Web.UI.HtmlControls.HtmlGenericControl"
        if ($typeName -eq "form") { $type = "System.Web.UI.HtmlControls.HtmlForm" }
        if ($typeName -eq "a") { $type = "System.Web.UI.HtmlControls.HtmlAnchor" }
        if ($typeName -eq "img") { $type = "System.Web.UI.HtmlControls.HtmlImage" }
        
        $sb.AppendLine("        protected global::$type $id;") | Out-Null
    }
    
    $sb.AppendLine("    }") | Out-Null
    if ($namespace) { $sb.AppendLine("}") | Out-Null }

    $designerPath = $f.FullName + ".designer.cs"
    Set-Content -Path $designerPath -Value $sb.ToString() -Encoding UTF8
}
