//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Monolito_4Am.Seguridad {
    public partial class RecuperarPassword {
        protected global::System.Web.UI.WebControls.Label lblStep1;
        protected global::System.Web.UI.WebControls.Label lblStep2;
        protected global::System.Web.UI.WebControls.Label lblStep3;
        protected global::System.Web.UI.WebControls.Panel pnlPaso1;
        protected global::System.Web.UI.WebControls.TextBox txtCedulaPaso1;
        protected global::System.Web.UI.WebControls.Button btnEnviarClave;
        protected global::System.Web.UI.WebControls.Panel pnlPaso2;
        protected global::System.Web.UI.WebControls.TextBox txtClaveTemporal;
        protected global::System.Web.UI.WebControls.Button btnValidarClave;
        protected global::System.Web.UI.WebControls.HyperLink hlWaMe;
        protected global::System.Web.UI.WebControls.Panel pnlPaso3;
        protected global::System.Web.UI.WebControls.TextBox txtNuevaPass;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmarPass;
        protected global::System.Web.UI.WebControls.Button btnCambiarPass;
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}

