//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Monolito_4Am.Seguridad {
    public partial class Registro {
        protected global::System.Web.UI.UpdatePanel upFoto;
        protected global::System.Web.UI.WebControls.TextBox txtCedula;
        protected global::System.Web.UI.WebControls.TextBox txtRolFijo;
        protected global::System.Web.UI.WebControls.TextBox txtNombres;
        protected global::System.Web.UI.WebControls.TextBox txtApellidos;
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;
        protected global::System.Web.UI.WebControls.TextBox txtCelular;
        protected global::System.Web.UI.WebControls.TextBox txtNick;
        protected global::System.Web.UI.WebControls.TextBox txtFechaNacimiento;
        protected global::System.Web.UI.WebControls.TextBox txtContrasena;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmar;
        protected global::System.Web.UI.WebControls.Image imgPreview;
        protected global::System.Web.UI.WebControls.Panel pnlFotoPlaceholder;
        protected global::System.Web.UI.WebControls.FileUpload fupFoto;
        protected global::System.Web.UI.WebControls.Button btnPrevisualizar;
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
        protected global::System.Web.UI.WebControls.LinkButton btnVolver;
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}

