//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Monolito_4Am.Seguridad {
    public partial class VerificarOTP {
        protected global::System.Web.UI.WebControls.Label lblCorreoDestino;
        protected global::System.Web.UI.WebControls.TextBox txtOTP;
        protected global::System.Web.UI.WebControls.Button btnVerificar;
        protected global::System.Web.UI.WebControls.Button btnReenviar;
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.HiddenField hfSecretNuevo;
        protected global::System.Web.UI.WebControls.Panel pnlConfigurar;
        protected global::System.Web.UI.WebControls.Panel pnlVerificar;
        protected global::System.Web.UI.WebControls.Image imgQR;
        protected global::System.Web.UI.WebControls.Label lblSecretVisible;
        protected global::System.Web.UI.WebControls.Label lblNombreUsuario;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}

