//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Monolito_4Am.Juego {
    public partial class Juego {
        protected global::System.Web.UI.WebControls.LinkButton btnBack;
        protected global::System.Web.UI.UpdatePanel upGame;
        protected global::System.Web.UI.Timer timerSequence;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblScore;
        protected global::System.Web.UI.WebControls.Button btn1;
        protected global::System.Web.UI.WebControls.Button btn2;
        protected global::System.Web.UI.WebControls.Button btn3;
        protected global::System.Web.UI.WebControls.Button btn4;
        protected global::System.Web.UI.WebControls.Button btn5;
        protected global::System.Web.UI.WebControls.Button btn6;
        protected global::System.Web.UI.WebControls.Button btn7;
        protected global::System.Web.UI.WebControls.Button btn8;
        protected global::System.Web.UI.WebControls.Button btn9;
        protected global::System.Web.UI.WebControls.Literal litSound;
        protected global::System.Web.UI.WebControls.Panel pnlStart;
        protected global::System.Web.UI.WebControls.Button btnStart;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Button btnRestart;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}

